image: node:16.19.0
stages: #Different stages which our pipeline need
  - lint
  - build
  - deploy


check: #Name of the job
  stage: lint #Tells job which stage it is
  script: #Scripts which need to be ran by the server
    - npm i
    - npm run lint
    - npm run ts

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: node:16
  script:
    - npm install
    - npm install -g firebase-tools
    - firebase experiments:enable webframeworks
    - firebase deploy --token 1//0gt60RleaTVUmCgYIARAAGBASNwF-L9Ir3DVtbcg7wnVIW426EFg3uLU0E7hocaKPPatvfKv4plHqyWem5maGA-xwwmigc8qSfYs --project possible-fabric-320701
  only:
    - develop