image: node:16.19.0
stages: #Different stages which our pipeline need
  - lint
  - build
  - deploy


check: #Name of the job
  stage: lint #Tells job which stage it is
  script: #Scripts which need to be ran by the server
    - npm i
    - npm run lint
    - npm run ts

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  image: node:16
  script:
    - npm install
    - npm install -g firebase-tools
    - firebase experiments:enable webframeworks
    - firebase deploy --token 1//0g5yYdNL3x9yFCgYIARAAGBASNwF-L9IreAG-94TfdEuXu7gfOGeFU11qJBxYoEPqLlcXuBpr5TrpNyZ-ej6aHWKfwbe7yqQaDAM --project ruralco-testing
  only:
    - develop

