image: node #The enviornment which we need
stages: #Different stages which our pipeline need
  - lint

check: #Name of the job
  stage: lint #Tells job which stage it is
  script: #Scripts which need to be ran by the server
    - npm i
    - npm run lint
    - npm run ts
