image: node:16.19.0
stages: #Different stages which our pipeline need
  - lint
  - build
  - deploy


check: #Name of the job
  stage: lint #Tells job which stage it is
  script: #Scripts which need to be ran by the server
    - npm i
    - npm run lint
    - npm run ts

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build

# deploy:
#   stage: deploy
#   image: node:16
#   script:
#     - npm install -g firebase-tools
#     - firebase use --add ruralco-f54ad
#     - firebase deploy --token "1//0gCNNPVXzH5dqCgYIARAAGBASNgF-L9IrW0TH1zS1ELZzmydCrC5iEg_Pkz1b-GHBJqmeq8me8MVD2O2Ufdxv8uQfAnH0xo69MA"
#   only:
#     - develop
